#!/bin/bash

cd examples
for DEMO_NAME in ./*
do
    if [ ! -d $DEMO_NAME ]; then
        continue
    fi
    if [ "${DEMO_NAME}" -eq "./raw_query" ]; then
        continue
    fi

    echo "Test ${DEMO_NAME}"
    cd $DEMO_NAME
    for SQL_FILENAME in ./*.sql
    do
        echo "RUN ${SQL_FILENAME}"
        syncany-sql ${SQL_FILENAME} || exit 255
    done

    echo
    cd ..
done

echo "succed"
cd ..
